name: Not Alone
description: This contains a nice description of the site.

markdown: kramdown

# always points to production site
canonical: https://www.notalone.gov

# any path prefix to apply, run with --baseurl="" in development
baseurl: ""

kramdown:
  parse_block_html: true

cachebuster: '0426131729'

include:
  - _navigation.json
